id: f5e459dfa5ed45f9b921a45fcc518a4e
initial_creation_type: ocr
source_metadata:
  volumes:
    70e81dce83be4aa988e087dfd5eb9075:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ཐེག་པ་གསུང་གི་སྒྲོན་མ།
      total_pages: 1902
      volume_number: 26
