id: DCB06B256
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T08:58:53+00:00'
last_modified: '2022-05-26T11:10:23.286697+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    e02a:
      image_group_id: I1PD95871
      title: ཐེག་པ་གསུང་གི་སྒྲོན་མ།
      total_pages: 1902
      order: 26
      base_file: e02a.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
